"use client";

import { useMemo, useState } from "react";
import { Search, SlidersHorizontal, Tags, Settings2, Trash2 } from "lucide-react";
import { deleteItem, updateCategory, updateRecurrence } from "@/app/(app)/perso/actions";

type Account={id:string;name:string};
type Category={id:string;name:string;parent_id:string|null;monthly_budget:number;account_id?:string|null;movement_type?:string;budget_period?:"monthly"|"specific_month";budget_month?:string|null;is_primary_income?:boolean};
type Recurrence={id:string;label:string;amount:number;end_date:string|null;is_active:boolean;movement_type:string;frequency:string;account_id:string;category_id?:string|null};

export function SettingsLists({accounts,categories,recurrences}:{accounts:Account[];categories:Category[];recurrences:Recurrence[]}){
 const [categoryQuery,setCategoryQuery]=useState("");const [categoryType,setCategoryType]=useState("all");const [categorySort,setCategorySort]=useState("name");
 const [recurrenceQuery,setRecurrenceQuery]=useState("");const [recurrenceStatus,setRecurrenceStatus]=useState("all");const [recurrenceType,setRecurrenceType]=useState("all");const [recurrenceSort,setRecurrenceSort]=useState("name");
 const filteredCategories=useMemo(()=>{const q=categoryQuery.trim().toLocaleLowerCase("fr");return [...categories].filter(c=>(!q||`${c.name} ${accounts.find(a=>a.id===c.account_id)?.name??""}`.toLocaleLowerCase("fr").includes(q))&&(categoryType==="all"||c.movement_type===categoryType)).sort((a,b)=>categorySort==="budget-desc"?Number(b.monthly_budget)-Number(a.monthly_budget):categorySort==="budget-asc"?Number(a.monthly_budget)-Number(b.monthly_budget):a.name.localeCompare(b.name,"fr"));},[accounts,categories,categoryQuery,categoryType,categorySort]);
 const filteredRecurrences=useMemo(()=>{const q=recurrenceQuery.trim().toLocaleLowerCase("fr");return [...recurrences].filter(r=>(!q||`${r.label} ${accounts.find(a=>a.id===r.account_id)?.name??""}`.toLocaleLowerCase("fr").includes(q))&&(recurrenceStatus==="all"||(recurrenceStatus==="active"&&r.is_active)||(recurrenceStatus==="paused"&&!r.is_active))&&(recurrenceType==="all"||r.movement_type===recurrenceType)).sort((a,b)=>recurrenceSort==="amount-desc"?Number(b.amount)-Number(a.amount):recurrenceSort==="amount-asc"?Number(a.amount)-Number(b.amount):a.label.localeCompare(b.label,"fr"));},[accounts,recurrences,recurrenceQuery,recurrenceStatus,recurrenceType,recurrenceSort]);
 return <div className="grid gap-7 xl:col-span-2 xl:grid-cols-2">
  <section className="rounded-3xl border border-black/10 bg-white p-6 shadow-sm"><Header icon={Tags} title="Catégories et budgets"/><Toolbar query={categoryQuery} setQuery={setCategoryQuery} placeholder="Rechercher une catégorie…"><select value={categoryType} onChange={e=>setCategoryType(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="all">Tous les types</option><option value="expense">Dépenses</option><option value="income">Revenus</option></select><Sort value={categorySort} onChange={setCategorySort} options={[["name","Nom A–Z"],["budget-desc","Budget décroissant"],["budget-asc","Budget croissant"]]}/></Toolbar><p className="mb-3 text-xs text-neutral-500">{filteredCategories.length} catégorie(s)</p>{filteredCategories.map(c=><div key={c.id} className="mb-3 rounded-2xl border p-4"><form action={updateCategory} className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="id" value={c.id}/><input type="hidden" name="movement_type" value={c.movement_type??"expense"}/><input name="name" defaultValue={c.name} className="rounded-xl border px-3 py-2"/><input name="monthly_budget" type="number" step="0.01" min="0" defaultValue={c.monthly_budget??0} className="rounded-xl border px-3 py-2"/><select name="budget_period" defaultValue={c.budget_period??"monthly"} className="rounded-xl border px-3 py-2"><option value="monthly">Tous les mois</option><option value="specific_month">Un mois précis</option></select><input name="budget_month" type="month" defaultValue={c.budget_month?.slice(0,7)??""} className="rounded-xl border px-3 py-2" title="À renseigner pour un budget limité à un mois"/><select name="account_id" defaultValue={c.account_id??""} className="rounded-xl border px-3 py-2"><option value="">Compte par défaut des mouvements</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{c.movement_type==="income"?<label className="flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><input type="checkbox" name="is_primary_income" defaultChecked={Boolean(c.is_primary_income)}/><span>Revenu principal / début de cycle</span></label>:null}<button className="rounded-xl bg-black px-4 py-2 text-sm text-white">Modifier</button></form><form action={deleteItem.bind(null,"personal_categories",c.id)} className="mt-2"><button className="flex items-center gap-2 text-xs text-red-700"><Trash2 size={13}/>Supprimer</button></form></div>)}</section>
  <section className="rounded-3xl border border-black/10 bg-white p-6 shadow-sm"><Header icon={Settings2} title="Mouvements réguliers"/><Toolbar query={recurrenceQuery} setQuery={setRecurrenceQuery} placeholder="Rechercher un mouvement régulier…"><select value={recurrenceStatus} onChange={e=>setRecurrenceStatus(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="all">Tous les états</option><option value="active">Actifs</option><option value="paused">Suspendus</option></select><select value={recurrenceType} onChange={e=>setRecurrenceType(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm"><option value="all">Tous les types</option><option value="expense">Dépenses</option><option value="income">Revenus</option><option value="transfer">Virements</option></select><Sort value={recurrenceSort} onChange={setRecurrenceSort} options={[["name","Libellé A–Z"],["amount-desc","Montant décroissant"],["amount-asc","Montant croissant"]]}/></Toolbar><p className="mb-3 text-xs text-neutral-500">{filteredRecurrences.length} mouvement(s)</p>{filteredRecurrences.map(r=><div key={r.id} className="mb-3 rounded-2xl border p-4"><form action={updateRecurrence} className="grid gap-2"><input type="hidden" name="id" value={r.id}/><input name="label" defaultValue={r.label} className="rounded-xl border px-3 py-2"/><div className="grid grid-cols-2 gap-2"><input name="amount" type="number" step="0.01" min="0.01" defaultValue={r.amount} className="rounded-xl border px-3 py-2"/><input name="end_date" type="date" defaultValue={r.end_date??""} className="rounded-xl border px-3 py-2"/></div><select name="is_active" defaultValue={String(r.is_active)} className="rounded-xl border px-3 py-2"><option value="true">Actif</option><option value="false">Suspendu</option></select><button className="rounded-xl bg-black px-4 py-2 text-sm text-white">Modifier</button></form><form action={deleteItem.bind(null,"personal_recurrences",r.id)} className="mt-2"><button className="flex items-center gap-2 text-xs text-red-700"><Trash2 size={13}/>Supprimer</button></form></div>)}</section>
 </div>;
}
function Header({icon:Icon,title}:{icon:any;title:string}){return <div className="mb-4 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-neutral-100"><Icon size={19}/></span><h2 className="text-xl font-semibold">{title}</h2></div>}
function Toolbar({query,setQuery,placeholder,children}:{query:string;setQuery:(v:string)=>void;placeholder:string;children:any}){return <div className="mb-3 grid gap-2 rounded-2xl bg-neutral-50 p-3"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder} className="h-10 w-full rounded-xl border bg-white pl-9 pr-3 text-sm"/></label><div className="grid gap-2 sm:grid-cols-2">{children}</div></div>}
function Sort({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="relative"><SlidersHorizontal size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400"/><select value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border bg-white pl-9 pr-3 text-sm">{options.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
