import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {createCommonCategory,createCommonMovement,createCommonRecurrence,createCommonSnapshot,deleteCommonCategory,deleteCommonMovement,deleteCommonRecurrence,saveCommonSettings,toggleCommonProrata} from "./actions";
import {Equal,Landmark,Percent,Trash2,TrendingUp} from "lucide-react";
export const dynamic="force-dynamic";
const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const money=(x:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(x),N=(x:any)=>Number(x??0)||0;
function F({label,...p}:any){return <label className="grid gap-1 text-sm"><span className="font-medium">{label}</span><input {...p} className="rounded-xl border border-black/10 px-3 py-2.5"/></label>}
function S({label,options,...p}:any){return <label className="grid gap-1 text-sm"><span className="font-medium">{label}</span><select {...p} className="rounded-xl border border-black/10 px-3 py-2.5">{options.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
function Notice({text,danger=false}:any){return <div className={`mx-3 mt-4 rounded-xl px-4 py-3 text-sm sm:mx-5 lg:mx-6 ${danger?"bg-red-50 text-red-800":"bg-emerald-50 text-emerald-800"}`}>{text}</div>}
function monthly(r:any){const a=N(r.amount),i=Math.max(1,N(r.interval_count));return r.frequency==="weekly"?a*52/12/i:r.frequency==="quarterly"?a/(3*i):r.frequency==="yearly"?a/(12*i):a/i}
function addMonths(d:Date,m:number){const x=new Date(d),day=x.getUTCDate();x.setUTCDate(1);x.setUTCMonth(x.getUTCMonth()+m);x.setUTCDate(Math.min(day,new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+1,0)).getUTCDate()));return x}
function occ(r:any,from:string,to:string){let d=new Date(`${r.start_date}T12:00:00Z`),end=new Date(`${to}T12:00:00Z`),sum=0,g=0;while(d<=end&&g++<1000){const iso=d.toISOString().slice(0,10);if(iso>=from&&(!r.end_date||iso<=r.end_date))sum++;if(r.frequency==="weekly")d=new Date(d.getTime()+7*86400000*Math.max(1,N(r.interval_count)));else d=addMonths(d,(r.frequency==="quarterly"?3:r.frequency==="yearly"?12:1)*Math.max(1,N(r.interval_count)))}return sum}
export default async function Page({searchParams}:{searchParams:Promise<any>}){
 const p=await searchParams,vue=p.vue==="budget"?"budget":"encours",supa=await createClient();
 const [{data:settings},{data:cats=[]},{data:snaps=[]},{data:movs=[]},{data:recs=[]}]=await Promise.all([supa.from("common_settings").select("*").eq("singleton",true).maybeSingle(),supa.from("common_categories").select("*").eq("is_active",true).order("name"),supa.from("common_balance_snapshots").select("*").order("snapshot_date",{ascending:false}),supa.from("common_movements").select("*").neq("status","cancelled").order("movement_date",{ascending:false}),supa.from("common_recurrences").select("*").eq("is_active",true).order("start_date")]);
 const st:any=settings??{},C:any[]=cats as any[],M:any[]=(movs as any[]).map(x=>({...x,amount:N(x.amount)})),R:any[]=(recs as any[]).map(x=>({...x,amount:N(x.amount)})),snap:any=(snaps as any[])[0];
 const snapDate=snap?.snapshot_date??today,cur=N(snap?.balance)+M.filter(x=>x.status==="completed"&&x.movement_date>snapDate&&x.movement_date<=today).reduce((a,x)=>a+(x.movement_type==="income"?x.amount:-x.amount),0);
 const monthEnd=new Date(Date.UTC(+today.slice(0,4),+today.slice(5,7),0)).toISOString().slice(0,10);
 const one=M.filter(x=>x.movement_date>today&&x.movement_date<=monthEnd).reduce((a,x)=>a+(x.movement_type==="income"?x.amount:-x.amount),0);
 const recurring=R.reduce((a,r)=>a+occ(r,today,monthEnd)*(r.movement_type==="income"?r.amount:-r.amount),0),forecast=cur+one+recurring;
 const r1=N(st.income_n1_person_1),r2=N(st.income_n1_person_2),rt=r1+r2,p1=rt?r1/rt:.5,p2=1-p1,expenses=R.filter(r=>r.movement_type==="expense"),incomes=R.filter(r=>r.movement_type==="income");
 const dep=expenses.reduce((a,r)=>a+monthly(r),0),cred=incomes.reduce((a,r)=>a+monthly(r),0),pro=expenses.filter(r=>r.prorate_by_income).reduce((a,r)=>a+monthly(r),0),half=dep-pro,need=Math.max(0,dep-cred),factor=dep?need/dep:0,a1=(pro*p1+half*.5)*factor,a2=(pro*p2+half*.5)*factor;
 return <main className="py-4 lg:py-6"><div>{p.erreur?<Notice danger text={p.erreur}/>:p.succes?<Notice text={p.succes}/>:null}
 <header className="border-b border-black/10 bg-white px-3 py-4 sm:px-5 lg:px-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-neutral-400">Espace partagé</p><h1 className="mt-1 text-2xl font-semibold">COMMUN</h1><p className="text-sm text-neutral-500">Indépendant des espaces PERSO.</p></header>
 <nav className="flex gap-2 border-b bg-neutral-100 px-3 py-1 sm:px-5 lg:px-6">{[["encours","En cours"],["budget","Budget"]].map(([id,l])=><Link key={id} href={`/commun?vue=${id}`} className={`px-4 py-2.5 text-sm font-medium ${vue===id?"bg-black text-white":"text-neutral-600"}`}>{l}</Link>)}</nav>
 {vue==="encours"?<div className="space-y-5 px-3 py-5 sm:px-5 lg:px-6">
  <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-black p-5 text-white"><Landmark size={20}/><p className="mt-4 text-xs text-neutral-400">{st.account_name??"Compte commun"} · aujourd’hui</p><p className="text-2xl font-semibold">{money(cur)}</p></div><div className="rounded-2xl border bg-white p-5"><TrendingUp size={20}/><p className="mt-4 text-xs text-neutral-500">Prévision fin de mois</p><p className={`text-2xl font-semibold ${forecast<0?"text-red-700":""}`}>{money(forecast)}</p></div></div>
  <details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Paramètres du compte et solde</summary><div className="mt-4 grid gap-5 md:grid-cols-2"><form action={saveCommonSettings} className="grid gap-3"><input type="hidden" name="return_view" value="encours"/><F label="Nom du compte" name="account_name" defaultValue={st.account_name??"Compte commun"}/><input type="hidden" name="person_1_name" value={st.person_1_name??"Personne 1"}/><input type="hidden" name="person_2_name" value={st.person_2_name??"Personne 2"}/><input type="hidden" name="income_n1_person_1" value={r1}/><input type="hidden" name="income_n1_person_2" value={r2}/><button className="rounded-xl bg-black p-3 text-white">Enregistrer</button></form><form action={createCommonSnapshot} className="grid gap-3"><F label="Solde constaté" name="balance" type="number" step=".01" defaultValue={cur}/><F label="Date" name="snapshot_date" type="date" defaultValue={today}/><button className="rounded-xl bg-black p-3 text-white">Mettre à jour le solde</button></form></div></details>
  <div className="grid gap-4 lg:grid-cols-3">
   <details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-semibold">+ Débit / crédit</summary><form action={createCommonMovement} className="mt-4 grid gap-3"><S label="Type" name="movement_type" options={[["expense","Dépense"],["income","Revenu"]]}/><F label="Libellé" name="label" required/><F label="Montant" name="amount" type="number" min=".01" step=".01" required/><F label="Date" name="movement_date" type="date" defaultValue={today}/><S label="État" name="status" options={[["planned","Prévu"],["completed","Déjà passé"]]}/><S label="Catégorie" name="category_id" options={[["","Sans catégorie"],...C.map(c=>[c.id,c.name])]}/><button className="rounded-xl bg-black p-3 text-white">Ajouter</button></form></details>
   <details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-semibold">+ Mouvement récurrent</summary><form action={createCommonRecurrence} className="mt-4 grid gap-3"><S label="Type" name="movement_type" options={[["expense","Dépense"],["income","Revenu"]]}/><F label="Libellé" name="label" required/><F label="Montant" name="amount" type="number" min=".01" step=".01"/><S label="Fréquence" name="frequency" options={[["monthly","Mensuelle"],["weekly","Hebdomadaire"],["quarterly","Trimestrielle"],["yearly","Annuelle"]]}/><F label="Tous les…" name="interval_count" type="number" min="1" defaultValue="1"/><F label="Début" name="start_date" type="date" defaultValue={today}/><F label="Fin (optionnelle)" name="end_date" type="date"/><S label="Catégorie" name="category_id" options={[["","Sans catégorie"],...C.map(c=>[c.id,c.name])]}/><button className="rounded-xl bg-black p-3 text-white">Ajouter</button></form></details>
   <details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Catégories</summary><form action={createCommonCategory} className="mt-4 grid gap-3"><F label="Nom" name="name"/><S label="Type" name="movement_type" options={[["expense","Dépense"],["income","Revenu"]]}/><button className="rounded-xl bg-black p-3 text-white">Ajouter</button></form><div className="mt-3 divide-y">{C.map(c=><div key={c.id} className="flex justify-between py-2 text-sm"><span>{c.name}</span><form action={deleteCommonCategory.bind(null,c.id)}><button><Trash2 size={16}/></button></form></div>)}</div></details>
  </div>
  <section className="rounded-2xl border bg-white"><h2 className="border-b px-4 py-3 font-semibold">Mouvements enregistrés</h2>{M.length?M.slice(0,30).map(m=><div key={m.id} className="flex items-center gap-3 border-b px-4 py-3 last:border-0"><div className="min-w-0 flex-1"><p className="truncate font-medium">{m.label}</p><p className="text-xs text-neutral-500">{m.movement_date} · {m.status==="completed"?"Passé":"Prévu"}</p></div><b className={m.movement_type==="expense"?"text-red-700":"text-emerald-700"}>{m.movement_type==="expense"?"−":"+"}{money(m.amount)}</b><form action={deleteCommonMovement.bind(null,m.id)}><button><Trash2 size={16}/></button></form></div>):<p className="p-4 text-sm text-neutral-500">Aucun mouvement.</p>}</section>
 </div>:null}
 {vue==="budget"?<div className="space-y-5 px-3 py-5 sm:px-5 lg:px-6">
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Revenus N-1</h2><p className="text-sm text-neutral-500">Ils servent uniquement aux dépenses que vous choisissez de proratiser.</p><form action={saveCommonSettings} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="return_view" value="budget"/><input type="hidden" name="account_name" value={st.account_name??"Compte commun"}/><F label="Nom personne 1" name="person_1_name" defaultValue={st.person_1_name??"Personne 1"}/><F label="Revenu N-1 personne 1" name="income_n1_person_1" type="number" min="0" step=".01" defaultValue={r1}/><F label="Nom personne 2" name="person_2_name" defaultValue={st.person_2_name??"Personne 2"}/><F label="Revenu N-1 personne 2" name="income_n1_person_2" type="number" min="0" step=".01" defaultValue={r2}/><button className="rounded-xl bg-black p-3 text-white sm:col-span-2">Enregistrer et recalculer</button></form><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl bg-neutral-100 p-3">{st.person_1_name??"Personne 1"} : <b>{(p1*100).toFixed(2)} %</b></div><div className="rounded-xl bg-neutral-100 p-3">{st.person_2_name??"Personne 2"} : <b>{(p2*100).toFixed(2)} %</b></div></div></section>
  <section className="rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-semibold">Dépenses récurrentes</h2><p className="text-xs text-neutral-500">Noir / % = prorata revenus N-1. Gris / = = 50/50.</p></div>{expenses.length?expenses.map(r=><div key={r.id} className="flex items-center gap-3 border-b p-4 last:border-0"><form action={toggleCommonProrata}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="value" value={String(!r.prorate_by_income)}/><button className={`grid size-9 place-items-center rounded-lg ${r.prorate_by_income?"bg-black text-white":"bg-neutral-100"}`}>{r.prorate_by_income?<Percent size={17}/>:<Equal size={17}/>}</button></form><div className="min-w-0 flex-1"><p className="font-medium">{r.label}</p><p className="text-xs text-neutral-500">{r.prorate_by_income?"Prorata revenus":"50/50"}</p></div><b>{money(monthly(r))}/mois</b><form action={deleteCommonRecurrence.bind(null,r.id)}><button><Trash2 size={16}/></button></form></div>):<p className="p-4 text-sm text-neutral-500">Crée les dépenses récurrentes dans « En cours ».</p>}</section>
  <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-neutral-500">Débits réguliers</p><b className="text-xl">{money(dep)}</b></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-neutral-500">Crédits réguliers</p><b className="text-xl">{money(cred)}</b></div><div className="rounded-2xl bg-black p-4 text-white"><p className="text-xs text-neutral-400">À financer / mois</p><b className="text-xl">{money(need)}</b></div></div>
  <section className="rounded-2xl border-2 border-black bg-white p-5"><h2 className="text-lg font-semibold">À verser chacun chaque mois</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-neutral-100 p-4"><p className="text-sm text-neutral-500">{st.person_1_name??"Personne 1"}</p><b className="text-2xl">{money(a1)}</b></div><div className="rounded-xl bg-neutral-100 p-4"><p className="text-sm text-neutral-500">{st.person_2_name??"Personne 2"}</p><b className="text-2xl">{money(a2)}</b></div></div><p className="mt-3 text-xs text-neutral-500">Les crédits réguliers sont déduits du besoin total. Les dépenses non sélectionnées restent automatiquement à 50/50.</p></section>
 </div>:null}</div></main>
}