-- COMMUN, totalement indépendant de PERSO
create extension if not exists pgcrypto;
create table if not exists public.common_settings (
 id uuid primary key default gen_random_uuid(), singleton boolean not null default true unique check(singleton),
 account_name text not null default 'Compte commun', person_1_name text not null default 'Personne 1', person_2_name text not null default 'Personne 2',
 income_n1_person_1 numeric(12,2) not null default 0 check(income_n1_person_1>=0), income_n1_person_2 numeric(12,2) not null default 0 check(income_n1_person_2>=0), updated_at timestamptz not null default now());
create table if not exists public.common_categories (id uuid primary key default gen_random_uuid(),name text not null,movement_type text not null check(movement_type in ('income','expense')),is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.common_balance_snapshots (id uuid primary key default gen_random_uuid(),balance numeric(12,2) not null,snapshot_date date not null unique,notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.common_recurrences (id uuid primary key default gen_random_uuid(),category_id uuid references public.common_categories(id) on delete set null,movement_type text not null check(movement_type in ('income','expense')),label text not null,amount numeric(12,2) not null check(amount>0),frequency text not null default 'monthly' check(frequency in ('weekly','monthly','quarterly','yearly')),interval_count integer not null default 1 check(interval_count>0),start_date date not null,end_date date,is_active boolean not null default true,prorate_by_income boolean not null default false,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.common_movements (id uuid primary key default gen_random_uuid(),category_id uuid references public.common_categories(id) on delete set null,movement_type text not null check(movement_type in ('income','expense')),label text not null,amount numeric(12,2) not null check(amount>0),movement_date date not null,status text not null default 'planned' check(status in ('planned','completed','cancelled')),recurrence_id uuid references public.common_recurrences(id) on delete set null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
insert into public.common_settings(singleton) values(true) on conflict(singleton) do nothing;
create or replace function public.can_access_common() returns boolean language sql stable security definer set search_path=public as $$ select auth.uid() is not null and (coalesce((auth.jwt()->'app_metadata'->>'photo_access')::boolean,false) or coalesce(auth.jwt()->'app_metadata'->>'role','')='personal'); $$;
alter table public.common_settings enable row level security; alter table public.common_categories enable row level security; alter table public.common_balance_snapshots enable row level security; alter table public.common_movements enable row level security; alter table public.common_recurrences enable row level security;
do $$ declare t text; begin foreach t in array array['common_settings','common_categories','common_balance_snapshots','common_movements','common_recurrences'] loop execute format('drop policy if exists common_shared_access on public.%I',t); execute format('create policy common_shared_access on public.%I for all to authenticated using (public.can_access_common()) with check (public.can_access_common())',t); end loop; end $$;
