import Link from "next/link";
import { Banknote, CalendarDays, Download, Landmark, Plus, ReceiptText, Save, Stethoscope } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createCharge, createFee, deleteFee, saveMonthlySettings, saveOsteoSettings, updateCharge, updateFee } from "./actions";

const money=(v:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(Number(v)||0);
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const monthName=(iso:string)=>{const s=new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(`${iso.slice(0,7)}-01T12:00:00`));return s.charAt(0).toUpperCase()+s.slice(1)};
const methodLabel=(m:string)=>m==="cb"?"Carte bleue":m==="cash"?"Espèces":"Chèque";
const monthsOf=(year:number)=>Array.from({length:12},(_,i)=>`${year}-${String(i+1).padStart(2,"0")}`);
const nextMonthStart=(month:string)=>{const [y,m]=month.split("-").map(Number);const d=new Date(Date.UTC(y,m,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-01`;};
const CORE_ORDER=["loyer","assurance_local","frais_bancaires","cotisations_trimestrielles","urssaf","care","agipi","rcp","cfe","doctolib","formation","gants_masques_blouse","restauration","frais_de_transport","materiel_de_bureau","blanchisserie","comptable","per","telephone"];
const CORE_LABELS:Record<string,string>={loyer:"Loyer saint père",assurance_local:"Assurance local",frais_bancaires:"Frais bancaires",cotisations_trimestrielles:"Cotisations trimestrielles",urssaf:"URSSAF",care:"CARE",agipi:"AGIPI",rcp:"RCP",cfe:"CFE",doctolib:"Doctolib Pro",formation:"Formation",gants_masques_blouse:"Gants, masques, blouse",restauration:"Restauration",frais_de_transport:"Frais de transport",materiel_de_bureau:"Matériel de bureau",blanchisserie:"Blanchisserie",comptable:"Comptable",per:"PER",telephone:"Téléphone"};

type SP={month?:string;view?:string;year?:string};
export async function OsteoContent({params,ownerId}:{params:SP;ownerId:string}){
 const p=params; const supabase=await createClient();
 const user={id:ownerId};
 const current=today(); const year=Math.max(2020,Math.min(2100,Number(p.year)||Number(current.slice(0,4)))); const selected=(p.month&&/^\d{4}-\d{2}$/.test(p.month)?p.month:current.slice(0,7)); const view=p.view==="2035"?"2035":"mensuel";
 const monthStart=`${selected}-01`; const monthEnd=nextMonthStart(selected);
 const accountsQuery=supabase.from("personal_accounts").select("id,name,account_type,is_active").eq("owner_id",user.id).eq("is_active",true).order("name");
 const settingsQuery=supabase.from("osteo_settings").select("bank_account_id").eq("owner_id",user.id).maybeSingle();
 const feesQuery=view==="2035"
  ? supabase.from("osteo_fees").select("id,fee_date,payment_method,amount").eq("owner_id",user.id).gte("fee_date",`${year}-01-01`).lte("fee_date",`${year}-12-31`).order("fee_date")
  : supabase.from("osteo_fees").select("id,fee_date,payment_method,amount").eq("owner_id",user.id).gte("fee_date",monthStart).lt("fee_date",monthEnd).order("fee_date");
 const chargesQuery=view==="2035"
  ? supabase.from("osteo_charges").select("id,month,due_day,category_key,label,amount,paid,project_to_personal,sort_order").eq("owner_id",user.id).gte("month",`${year}-01-01`).lte("month",`${year}-12-01`).order("month").order("sort_order")
  : supabase.from("osteo_charges").select("id,month,due_day,category_key,label,amount,paid,project_to_personal,sort_order").eq("owner_id",user.id).eq("month",monthStart).order("sort_order");
 const monthlyQuery=view==="2035"
  ? supabase.from("osteo_monthly_settings").select("month,sublease_income,km_per_day,benefit_previous_year").eq("owner_id",user.id).gte("month",`${year}-01-01`).lte("month",`${year}-12-01`).order("month")
  : supabase.from("osteo_monthly_settings").select("month,sublease_income,km_per_day,benefit_previous_year").eq("owner_id",user.id).eq("month",monthStart);
 const timed = async (name:string, q:any) => {
   const started = Date.now();
   const result = await q;
   console.log(`[OSTEO PERF] ${name}: ${Date.now()-started} ms`, result.error?.message ?? "OK");
   return result;
 };
 const [accountsResult,settingsResult,feesResult,chargesResult,monthlyResult]=await Promise.all([
   timed("accounts", accountsQuery),
   timed("settings", settingsQuery),
   timed("fees", feesQuery),
   timed("charges", chargesQuery),
   timed("monthly", monthlyQuery),
 ]);
 const loadError=accountsResult.error??settingsResult.error??feesResult.error??chargesResult.error??monthlyResult.error;
 if(loadError){
  return <main className="osteo-page mx-auto max-w-[900px] p-4 sm:p-6"><section className="rounded-3xl border border-red-400/30 bg-[#1B1D1B] p-5"><div className="flex items-center gap-2 text-[#D2AE57]"><Stethoscope size={21}/><span className="text-xs font-semibold uppercase tracking-[.18em]">OSTEO</span></div><h1 className="mt-3 text-xl font-semibold text-white">Impossible de charger les données OSTEO</h1><p className="mt-2 text-sm text-white/65">La page répond, mais une requête Supabase a échoué : {loadError.message}</p><p className="mt-2 text-xs text-white/45">Vérifie que la migration OSTEO est bien appliquée au projet Supabase utilisé par VSMI.</p></section></main>;
 }
 const accounts=accountsResult.data??[]; const settings=settingsResult.data; const fees=feesResult.data??[]; const charges=chargesResult.data??[]; const monthly=monthlyResult.data??[];
 const selectedFees=view==="mensuel"?(fees as any[]):(fees as any[]).filter(f=>f.fee_date.startsWith(selected)); const selectedCharges=view==="mensuel"?(charges as any[]):(charges as any[]).filter(c=>c.month.startsWith(selected)); const ms=(monthly as any[]).find(m=>m.month.startsWith(selected))??{sublease_income:250,km_per_day:12,benefit_previous_year:0};
 const feeTotals={cb:0,cash:0,cheque:0}; for(const f of selectedFees) feeTotals[f.payment_method as keyof typeof feeTotals]+=Number(f.amount)||0;
 const receipts=feeTotals.cb+feeTotals.cash+feeTotals.cheque; const expenses=selectedCharges.reduce((s,c)=>s+(Number(c.amount)||0),0); const sublet=Number(ms.sublease_income)||0; const benefit=receipts+sublet-expenses; const days=new Set(selectedFees.map(f=>f.fee_date)).size; const patients=selectedFees.length; const km=days*(Number(ms.km_per_day)||0);
 const monthKeys=view==="2035"?monthsOf(year):[]; const monthlyByKey=new Map((monthly as any[]).map(m=>[m.month.slice(0,7),m]));
 const feesByMonth=new Map<string,any[]>(); if(view==="2035") for(const f of fees as any[]){const k=f.fee_date.slice(0,7);feesByMonth.set(k,[...(feesByMonth.get(k)??[]),f]);}
 const chargesByMonth=new Map<string,any[]>(); if(view==="2035") for(const c of charges as any[]){const k=c.month.slice(0,7);chargesByMonth.set(k,[...(chargesByMonth.get(k)??[]),c]);}
 const annual=view==="2035"?monthKeys.map(k=>{const fs=feesByMonth.get(k)??[],cs=chargesByMonth.get(k)??[],set=monthlyByKey.get(k)??{sublease_income:250,km_per_day:12,benefit_previous_year:0};let cb=0,ch=0,cash=0;for(const f of fs){const amount=Number(f.amount)||0;if(f.payment_method==="cb")cb+=amount;else if(f.payment_method==="cheque")ch+=amount;else if(f.payment_method==="cash")cash+=amount;}const exp=cs.reduce((sum,c)=>sum+(Number(c.amount)||0),0);const distinct=new Set(fs.map(f=>f.fee_date)).size;const sublet=Number(set.sublease_income)||0;return{k,cbCheque:cb+ch,cash,sublet,total:cb+ch+cash+sublet,expenses:exp,benefit:cb+ch+cash+sublet-exp,patients:fs.length,days:distinct,km:distinct*(Number(set.km_per_day)||0),prev:Number(set.benefit_previous_year)||0,charges:cs};}):[];
 return <main className="osteo-page mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8">
  <section className="osteo-panel flex flex-col gap-4 rounded-3xl border border-white/10 bg-[#1B1D1B] p-5 sm:flex-row sm:items-center sm:justify-between">
   <div><div className="flex items-center gap-2 text-[#D2AE57]"><Stethoscope size={21}/><span className="text-xs font-semibold uppercase tracking-[.18em]">OSTEO</span></div><h1 className="mt-2 text-2xl font-semibold text-white">Activité de Laure</h1><p className="mt-1 text-sm text-white/55">Honoraires, charges, projection bancaire et vue 2035.</p></div>
   <div className="flex flex-wrap gap-2"><Link href={`/osteo?view=mensuel&month=${selected}&year=${year}`} className={`rounded-2xl px-4 py-2.5 text-sm font-semibold ${view==="mensuel"?"bg-[#D2AE57] text-black":"bg-white/8 text-white"}`}><CalendarDays className="mr-2 inline" size={16}/>Mensuel</Link><Link href={`/osteo?view=2035&year=${year}`} className={`rounded-2xl px-4 py-2.5 text-sm font-semibold ${view==="2035"?"bg-[#D2AE57] text-black":"bg-white/8 text-white"}`}><ReceiptText className="mr-2 inline" size={16}/>2035 annuelle</Link></div>
  </section>
  <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-4"><form action={saveOsteoSettings} className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><label className="text-sm text-white/70">Compte bancaire dédié<select name="bank_account_id" defaultValue={settings?.bank_account_id??""} className="osteo-input mt-1 w-full rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"><option value="">— Aucun compte lié —</option>{(accounts as any[]).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="rounded-xl bg-[#D2AE57] px-4 py-2.5 font-semibold text-black"><Save className="mr-2 inline" size={16}/>Enregistrer</button></form><p className="mt-2 text-xs text-white/45">CB et chèques sont synchronisés vers ce compte. Les espèces restent uniquement dans OSTEO. Les charges projetables (URSSAF, frais bancaires, CARE, téléphone, loyer, Doctolib, AGIPI, comptable, cotisations trimestrielles, RCP, Assurance local, CFE) alimentent les mouvements à venir.</p></section>
  {view==="mensuel"?<>
   <section className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
    <div className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-white/40">Saisie rapide</p><h2 className="mt-1 text-lg font-semibold text-white">+ Honoraires</h2></div><Banknote className="text-[#D2AE57]"/></div><form action={createFee} className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm text-white/65">Date<input type="date" name="fee_date" defaultValue={current} required className="osteo-input mt-1 w-full rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"/></label><label className="text-sm text-white/65">Règlement<select name="payment_method" className="osteo-input mt-1 w-full rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"><option value="cb">CB</option><option value="cash">Espèces</option><option value="cheque">Chèque</option></select></label><label className="text-sm text-white/65">Montant<input type="number" name="amount" step="0.01" min="0.01" required className="osteo-input mt-1 w-full rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"/></label><button className="sm:col-span-3 rounded-xl bg-[#D2AE57] px-4 py-3 font-semibold text-black"><Plus className="mr-2 inline" size={17}/>Ajouter l'honoraire</button></form></div>
    <div className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-white">{monthName(selected)}</h2><div className="flex gap-2"><form action="/osteo" className="flex gap-1"><input type="hidden" name="view" value="mensuel"/><input type="month" name="month" defaultValue={selected} className="osteo-input rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2 text-white"/><button className="rounded-xl border border-white/15 px-3 py-2 text-sm text-white/70">Afficher</button></form><a href={`/osteo/export?scope=month&month=${selected}`} className="rounded-xl border border-[#D2AE57]/40 px-3 py-2 text-sm text-[#E0C27E]"><Download className="mr-1 inline" size={15}/>PDF</a></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Chèques + CB" value={money(feeTotals.cheque+feeTotals.cb)}/><Metric label="Espèces" value={money(feeTotals.cash)}/><Metric label="Sous-location" value={money(sublet)}/><Metric label="Dépenses" value={money(expenses)}/><Metric label="Bénéfice" value={money(benefit)} accent={benefit>=0}/><Metric label="Patients / jours" value={`${patients} / ${days}`}/></div></div>
   </section>
   <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Paramètres du mois</h2><span className="text-xs text-white/40">Tous les montants restent modifiables</span></div><form action={saveMonthlySettings} className="mt-4 grid gap-3 sm:grid-cols-4"><input type="hidden" name="month" value={selected}/><Field name="sublease_income" label="Sous-location" value={sublet}/><Field name="km_per_day" label="Km / jour travaillé" value={Number(ms.km_per_day)||0}/><Field name="benefit_previous_year" label="Bénéfice N-1" value={Number(ms.benefit_previous_year)||0}/><div className="flex items-end"><button className="w-full rounded-xl bg-[#D2AE57] px-4 py-2.5 font-semibold text-black">Enregistrer</button></div></form><p className="mt-3 text-sm text-white/50">Km du mois : <strong className="text-white">{km.toFixed(0)} km</strong></p></section>
   <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><h2 className="text-lg font-semibold text-white">Honoraires du mois</h2><div className="mt-4 space-y-2">{selectedFees.length?selectedFees.map((f:any)=><form action={updateFee} key={f.id} className="osteo-row grid gap-2 rounded-2xl border border-white/10 bg-[#292B28] p-3 sm:grid-cols-[150px_150px_1fr_auto_auto] sm:items-center"><input type="hidden" name="id" value={f.id}/><input type="date" name="fee_date" defaultValue={f.fee_date} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><select name="payment_method" defaultValue={f.payment_method} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"><option value="cb">CB</option><option value="cash">Espèces</option><option value="cheque">Chèque</option></select><input name="amount" type="number" step="0.01" min="0.01" defaultValue={Number(f.amount)} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><button className="rounded-xl border border-[#D2AE57]/35 px-3 py-2 text-sm text-[#E0C27E]">Modifier</button><button formAction={deleteFee} className="rounded-xl border border-red-500/30 px-3 py-2 text-sm text-red-300">Supprimer</button></form>):<p className="text-sm text-white/45">Aucun honoraire pour ce mois.</p>}</div></section>
   <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Charges du mois</h2><span className="text-sm text-white/45">{money(expenses)}</span></div><div className="mt-4 space-y-2">{selectedCharges.map((c:any)=><form action={updateCharge} key={c.id} className="osteo-row grid gap-2 rounded-2xl border border-white/10 bg-[#292B28] p-3 md:grid-cols-[70px_1fr_130px_130px_150px_auto] md:items-center"><input type="hidden" name="id" value={c.id}/><input name="due_day" type="number" min="1" max="31" defaultValue={c.due_day} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><input name="label" defaultValue={c.label} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><input name="amount" type="number" step="0.01" min="0" defaultValue={Number(c.amount)} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><label className="flex items-center gap-2 text-sm text-white/65"><input name="paid" type="checkbox" defaultChecked={c.paid}/>Payée</label><label className="flex items-center gap-2 text-sm text-white/65"><input name="project_to_personal" type="checkbox" defaultChecked={c.project_to_personal}/>Vers PERSO</label><button className="rounded-xl border border-[#D2AE57]/35 px-3 py-2 text-sm text-[#E0C27E]">Enregistrer</button></form>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-[#E0C27E]">+ Ajouter une charge</summary><form action={createCharge} className="mt-3 grid gap-2 sm:grid-cols-4"><input type="hidden" name="month" value={selected}/><input name="due_day" type="number" min="1" max="31" defaultValue="1" className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-3 py-2 text-white"/><input name="label" placeholder="Libellé" required className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-3 py-2 text-white"/><input name="amount" type="number" step="0.01" min="0" placeholder="Montant" className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-3 py-2 text-white"/><label className="flex items-center gap-2 text-sm text-white/65"><input name="project_to_personal" type="checkbox"/>Projeter dans PERSO</label><button className="rounded-xl bg-[#D2AE57] px-4 py-2 font-semibold text-black sm:col-span-4">Ajouter</button></form></details></section>
  </>:<section className="osteo-panel overflow-hidden rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-white/40">Déclaration 2035</p><h2 className="mt-1 text-xl font-semibold text-white">Vue annuelle {year}</h2></div><div className="flex gap-2"><a href={`/osteo/export?scope=year&year=${year}`} className="rounded-xl border border-[#D2AE57]/40 px-3 py-2 text-sm text-[#E0C27E]"><Download className="mr-1 inline" size={15}/>Exporter PDF</a><form action="/osteo"><input type="hidden" name="view" value="2035"/><input name="year" type="number" defaultValue={year} className="osteo-input w-24 rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2 text-white"/></form></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-[1200px] w-full border-separate border-spacing-0 text-sm"><thead><tr><Th>2035</Th>{annual.map(x=><Th key={x.k}><Link href={`/osteo?view=mensuel&month=${x.k}&year=${year}`} className="hover:text-[#E0C27E]">{monthName(x.k).split(" ")[0]}</Link></Th>)}<Th>Total</Th></tr></thead><tbody><AnnualRow label="Chèques et CB" values={annual.map(x=>x.cbCheque)}/><AnnualRow label="Espèces" values={annual.map(x=>x.cash)}/><AnnualRow label="Sous loc" values={annual.map(x=>x.sublet)}/><AnnualRow label="Total revenus" values={annual.map(x=>x.total)} strong/><tr><td colSpan={14} className="h-3"/></tr>{CORE_ORDER.map(key=><AnnualRow key={key} label={CORE_LABELS[key]} values={annual.map(x=>Number(x.charges.find((c:any)=>c.category_key===key)?.amount||0))}/>) }<AnnualRow label="Dépenses" values={annual.map(x=>x.expenses)} strong/><AnnualRow label="Bénéfice" values={annual.map(x=>x.benefit)} strong/><AnnualRow label="Nbr patients" values={annual.map(x=>x.patients)} plain/><AnnualRow label="Nbre de jours" values={annual.map(x=>x.days)} plain/><AnnualRow label="Km/mois" values={annual.map(x=>x.km)} plain/><AnnualRow label={`Bénéfices ${year-1}`} values={annual.map(x=>x.prev)}/></tbody></table></div><p className="mt-4 text-xs text-white/45">Les valeurs annuelles sont recalculées à partir des honoraires, charges et paramètres mensuels. Pour modifier une cellule, ouvre le mois correspondant dans la vue Mensuel.</p></section>}
 </main>
}
function Metric({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div className="osteo-metric rounded-2xl border border-white/10 bg-[#292B28] p-3"><p className="text-xs text-white/45">{label}</p><p className={`mt-1 text-lg font-semibold ${accent===undefined?"text-white":accent?"text-emerald-300":"text-red-300"}`}>{value}</p></div>}
function Field({name,label,value}:{name:string;label:string;value:number}){return <label className="text-sm text-white/65">{label}<input name={name} type="number" step="0.01" defaultValue={value} className="osteo-input mt-1 w-full rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"/></label>}
function Th({children}:{children:React.ReactNode}){return <th className="sticky top-0 border-b border-white/15 bg-[#222422] px-3 py-2 text-right text-xs font-semibold text-white first:left-0 first:z-10 first:text-left">{children}</th>}
function AnnualRow({label,values,strong=false,plain=false}:{label:string;values:number[];strong?:boolean;plain?:boolean}){const total=values.reduce((s,v)=>s+Number(v||0),0);return <tr className={strong?"font-semibold":""}><td className="sticky left-0 border-b border-white/8 bg-[#1B1D1B] px-3 py-2 text-white">{label}</td>{values.map((v,i)=><td key={i} className="border-b border-white/8 px-3 py-2 text-right text-white/75">{plain?Number(v||0).toFixed(0):money(v)}</td>)}<td className="border-b border-white/8 px-3 py-2 text-right text-[#E0C27E]">{plain?total.toFixed(0):money(total)}</td></tr>}
