import Link from "next/link";
import { Activity, ArrowLeft, ArrowRight, Banknote, CalendarDays, Download, Plus, ReceiptText, Save, Stethoscope } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createCharge, createFee, deleteFee, saveMonthlySettings, saveOsteoSettings, updateCharge, updateFee } from "./actions";

const money=(v:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(Number(v)||0);
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const monthName=(iso:string)=>{const s=new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(`${iso.slice(0,7)}-01T12:00:00`));return s.charAt(0).toUpperCase()+s.slice(1)};
const shortMonth=(iso:string)=>new Intl.DateTimeFormat("fr-FR",{month:"short"}).format(new Date(`${iso.slice(0,7)}-01T12:00:00`)).replace(".","");
const methodLabel=(m:string)=>m==="cb"?"Carte bleue":m==="cash"?"Espèces":"Chèque";
const monthsOf=(year:number)=>Array.from({length:12},(_,i)=>`${year}-${String(i+1).padStart(2,"0")}`);
const nextMonthStart=(month:string)=>{const [y,m]=month.split("-").map(Number);const d=new Date(Date.UTC(y,m,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-01`;};
const CORE_ORDER=["loyer","assurance_local","frais_bancaires","cotisations_trimestrielles","urssaf","care","agipi","rcp","cfe","doctolib","formation","gants_masques_blouse","restauration","frais_de_transport","materiel_de_bureau","blanchisserie","comptable","per","telephone"];
const CORE_LABELS:Record<string,string>={loyer:"Loyer saint père",assurance_local:"Assurance local",frais_bancaires:"Frais bancaires",cotisations_trimestrielles:"Cotisations trimestrielles",urssaf:"URSSAF",care:"CARE",agipi:"AGIPI",rcp:"RCP",cfe:"CFE",doctolib:"Doctolib Pro",formation:"Formation",gants_masques_blouse:"Gants, masques, blouse",restauration:"Restauration",frais_de_transport:"Frais de transport",materiel_de_bureau:"Matériel de bureau",blanchisserie:"Blanchisserie",comptable:"Comptable",per:"PER",telephone:"Téléphone"};

type SP={month?:string;view?:string;year?:string};
type AnnualMonth={k:string;cbCheque:number;cash:number;sublet:number;total:number;expenses:number;benefit:number;patients:number;days:number;km:number;prev:number;charges:any[]};

export async function OsteoContent({params,ownerId}:{params:SP;ownerId:string}){
 const supabase=await createClient();
 const current=today();
 const currentYear=Number(current.slice(0,4));
 const requestedMonth=pMonth(params.month,current.slice(0,7));
 const view=params.view==="2035"?"2035":params.view==="analyse"?"analyse":"mensuel";
 const year=view==="analyse"?currentYear:Math.max(2020,Math.min(2100,Number(params.year)||Number(requestedMonth.slice(0,4))||currentYear));
 const selected=requestedMonth.startsWith(`${year}-`)?requestedMonth:`${year}-${current.slice(5,7)}`;
 const monthStart=`${selected}-01`; const monthEnd=nextMonthStart(selected);
 const annualView=view!=="mensuel";

 const accountsQuery=supabase.from("personal_accounts").select("id,name,account_type,is_active").eq("owner_id",ownerId).eq("is_active",true).order("name");
 const settingsQuery=supabase.from("osteo_settings").select("bank_account_id").eq("owner_id",ownerId).maybeSingle();
 const feesQuery=annualView
  ? supabase.from("osteo_fees").select("id,fee_date,payment_method,amount").eq("owner_id",ownerId).gte("fee_date",`${year}-01-01`).lte("fee_date",`${year}-12-31`).order("fee_date",{ascending:true})
  : supabase.from("osteo_fees").select("id,fee_date,payment_method,amount").eq("owner_id",ownerId).gte("fee_date",monthStart).lt("fee_date",monthEnd).order("fee_date",{ascending:false}).order("id",{ascending:false});
 const chargesQuery=annualView
  ? supabase.from("osteo_charges").select("id,month,due_day,category_key,label,amount,paid,project_to_personal,sort_order").eq("owner_id",ownerId).gte("month",`${year}-01-01`).lte("month",`${year}-12-01`).order("month").order("sort_order")
  : supabase.from("osteo_charges").select("id,month,due_day,category_key,label,amount,paid,project_to_personal,sort_order").eq("owner_id",ownerId).eq("month",monthStart).order("sort_order");
 const monthlyQuery=annualView
  ? supabase.from("osteo_monthly_settings").select("month,sublease_income,km_per_day,benefit_previous_year").eq("owner_id",ownerId).gte("month",`${year}-01-01`).lte("month",`${year}-12-01`).order("month")
  : supabase.from("osteo_monthly_settings").select("month,sublease_income,km_per_day,benefit_previous_year").eq("owner_id",ownerId).eq("month",monthStart);

 const [accountsResult,settingsResult,feesResult,chargesResult,monthlyResult]=await Promise.all([accountsQuery,settingsQuery,feesQuery,chargesQuery,monthlyQuery]);
 const loadError=accountsResult.error??settingsResult.error??feesResult.error??chargesResult.error??monthlyResult.error;
 if(loadError){return <main className="osteo-page mx-auto max-w-[900px] p-4 sm:p-6"><section className="osteo-panel rounded-3xl border border-red-400/30 bg-[#1B1D1B] p-5"><div className="flex items-center gap-2 text-[#D2AE57]"><Stethoscope size={21}/><span className="text-xs font-semibold uppercase tracking-[.18em]">OSTEO</span></div><h1 className="mt-3 text-xl font-semibold text-white">Impossible de charger les données OSTEO</h1><p className="mt-2 text-sm text-white/65">{loadError.message}</p></section></main>}

 const accounts=accountsResult.data??[]; const settings=settingsResult.data; const fees=feesResult.data??[]; const charges=chargesResult.data??[]; const monthly=monthlyResult.data??[];
 const selectedFees=annualView?(fees as any[]).filter(f=>f.fee_date.startsWith(selected)):(fees as any[]);
 const selectedCharges=annualView?(charges as any[]).filter(c=>c.month.startsWith(selected)):(charges as any[]);
 const ms=(monthly as any[]).find(m=>m.month.startsWith(selected))??{sublease_income:250,km_per_day:12,benefit_previous_year:0};
 const feeTotals={cb:0,cash:0,cheque:0}; for(const f of selectedFees) feeTotals[f.payment_method as keyof typeof feeTotals]+=Number(f.amount)||0;
 const receipts=feeTotals.cb+feeTotals.cash+feeTotals.cheque; const expenses=selectedCharges.reduce((s,c)=>s+(Number(c.amount)||0),0); const sublet=Number(ms.sublease_income)||0; const benefit=receipts+sublet-expenses; const days=new Set(selectedFees.map(f=>f.fee_date)).size; const patients=selectedFees.length; const km=days*(Number(ms.km_per_day)||0);

 const monthKeys=monthsOf(year); const monthlyByKey=new Map((monthly as any[]).map(m=>[m.month.slice(0,7),m]));
 const feesByMonth=new Map<string,any[]>(); if(annualView) for(const f of fees as any[]){const k=f.fee_date.slice(0,7);feesByMonth.set(k,[...(feesByMonth.get(k)??[]),f]);}
 const chargesByMonth=new Map<string,any[]>(); if(annualView) for(const c of charges as any[]){const k=c.month.slice(0,7);chargesByMonth.set(k,[...(chargesByMonth.get(k)??[]),c]);}
 const annual:AnnualMonth[]=annualView?monthKeys.map(k=>{const fs=feesByMonth.get(k)??[],cs=chargesByMonth.get(k)??[],set:any=monthlyByKey.get(k)??{sublease_income:250,km_per_day:12,benefit_previous_year:0};let cb=0,ch=0,cash=0;for(const f of fs){const amount=Number(f.amount)||0;if(f.payment_method==="cb")cb+=amount;else if(f.payment_method==="cheque")ch+=amount;else if(f.payment_method==="cash")cash+=amount;}const exp=cs.reduce((sum,c)=>sum+(Number(c.amount)||0),0);const distinct=new Set(fs.map(f=>f.fee_date)).size;const sub=Number(set.sublease_income)||0;return{k,cbCheque:cb+ch,cash,sublet:sub,total:cb+ch+cash+sub,expenses:exp,benefit:cb+ch+cash+sub-exp,patients:fs.length,days:distinct,km:distinct*(Number(set.km_per_day)||0),prev:Number(set.benefit_previous_year)||0,charges:cs};}):[];

 return <main className="osteo-page mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8">
  <section className="osteo-panel flex flex-col gap-4 rounded-3xl border border-white/10 bg-[#1B1D1B] p-5 sm:flex-row sm:items-center sm:justify-between">
   <div><div className="flex items-center gap-2 text-[#D2AE57]"><Stethoscope size={21}/><span className="text-xs font-semibold uppercase tracking-[.18em]">OSTEO</span></div><h1 className="mt-2 text-2xl font-semibold text-white">Activité de Laure</h1><p className="mt-1 text-sm text-white/55">Honoraires, charges, 2035 et analyse d’activité.</p></div>
   <div className="flex flex-wrap gap-2">
    <NavButton active={view==="mensuel"} href={`/osteo?view=mensuel&month=${selected}&year=${year}`} icon={<CalendarDays size={16}/>}>Mensuel</NavButton>
    <NavButton active={view==="2035"} href={`/osteo?view=2035&year=${year}`} icon={<ReceiptText size={16}/>}>2035 annuelle</NavButton>
    <NavButton active={view==="analyse"} href="/osteo?view=analyse" icon={<Activity size={16}/>}>Analyse</NavButton>
   </div>
  </section>

  <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-4"><form action={saveOsteoSettings} className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><label className="text-sm text-white/70">Compte bancaire dédié<select name="bank_account_id" defaultValue={settings?.bank_account_id??""} className="osteo-input mt-1 w-full rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"><option value="">— Aucun compte lié —</option>{(accounts as any[]).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="rounded-xl bg-[#D2AE57] px-4 py-2.5 font-semibold text-black"><Save className="mr-2 inline" size={16}/>Enregistrer</button></form><p className="mt-2 text-xs text-white/45">CB et chèques sont synchronisés vers ce compte. Les espèces restent uniquement dans OSTEO.</p></section>

  {view==="mensuel"?<MonthlyView year={year} selected={selected} feeTotals={feeTotals} sublet={sublet} expenses={expenses} benefit={benefit} patients={patients} days={days} km={km} ms={ms} fees={selectedFees} charges={selectedCharges}/>:view==="2035"?<Annual2035 year={year} annual={annual}/>:<AnalysisView year={year} annual={annual} currentMonth={current.slice(0,7)}/>} 
 </main>
}

function MonthlyView({year,selected,feeTotals,sublet,expenses,benefit,patients,days,km,ms,fees,charges}:{year:number;selected:string;feeTotals:{cb:number;cash:number;cheque:number};sublet:number;expenses:number;benefit:number;patients:number;days:number;km:number;ms:any;fees:any[];charges:any[]}){
 const months=monthsOf(year); const idx=months.indexOf(selected); const prev=idx>0?months[idx-1]:null; const next=idx>=0&&idx<11?months[idx+1]:null;
 return <>
  <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-white/40">Navigation</p><h2 className="mt-1 text-lg font-semibold text-white">{monthName(selected)}</h2></div><div className="flex gap-2">{prev?<Link href={`/osteo?view=mensuel&month=${prev}&year=${year}`} className="osteo-secondary-button"><ArrowLeft size={16}/></Link>:<span className="osteo-secondary-button opacity-30"><ArrowLeft size={16}/></span>}{next?<Link href={`/osteo?view=mensuel&month=${next}&year=${year}`} className="osteo-secondary-button"><ArrowRight size={16}/></Link>:<span className="osteo-secondary-button opacity-30"><ArrowRight size={16}/></span>}</div></div><div className="mt-3 grid grid-cols-3 gap-1.5 sm:grid-cols-6 lg:grid-cols-12">{months.map(m=><Link key={m} href={`/osteo?view=mensuel&month=${m}&year=${year}`} className={`rounded-xl border px-2 py-2 text-center text-xs font-semibold ${m===selected?"border-[#D2AE57] bg-[#D2AE57] text-black":"border-white/10 bg-white/5 text-white/65 hover:border-[#D2AE57]/50"}`}>{shortMonth(m)}</Link>)}</div></section>
  <section className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
   <div className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-white/40">Saisie rapide</p><h2 className="mt-1 text-lg font-semibold text-white">+ Honoraires</h2></div><Banknote className="text-[#D2AE57]"/></div><form action={createFee} className="mt-4 grid gap-3 sm:grid-cols-4"><input name="fee_date" type="date" required defaultValue={selected===today().slice(0,7)?today():`${selected}-01`} className="osteo-input rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"/><select name="payment_method" defaultValue="cb" className="osteo-input rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"><option value="cb">CB</option><option value="cash">Espèces</option><option value="cheque">Chèque</option></select><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Montant" className="osteo-input rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"/><button className="rounded-xl bg-[#D2AE57] px-4 py-2.5 font-semibold text-black"><Plus className="mr-1 inline" size={16}/>Ajouter</button></form></div>
   <div className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-white">{monthName(selected)}</h2><a href={`/osteo/export?scope=month&month=${selected}`} className="osteo-secondary-button"><Download size={15}/>PDF</a></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Chèques + CB" value={money(feeTotals.cheque+feeTotals.cb)}/><Metric label="Espèces" value={money(feeTotals.cash)}/><Metric label="Sous-location" value={money(sublet)}/><Metric label="Dépenses" value={money(expenses)}/><Metric label="Bénéfice" value={money(benefit)} accent={benefit>=0}/><Metric label="Patients / jours" value={`${patients} / ${days}`}/></div></div>
  </section>
  <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Paramètres du mois</h2><span className="text-xs text-white/40">Montants modifiables</span></div><form action={saveMonthlySettings} className="mt-4 grid gap-3 sm:grid-cols-4"><input type="hidden" name="month" value={selected}/><Field name="sublease_income" label="Sous-location" value={sublet}/><Field name="km_per_day" label="Km / jour travaillé" value={Number(ms.km_per_day)||0}/><Field name="benefit_previous_year" label="Bénéfice N-1" value={Number(ms.benefit_previous_year)||0}/><div className="flex items-end"><button className="w-full rounded-xl bg-[#D2AE57] px-4 py-2.5 font-semibold text-black">Enregistrer</button></div></form><p className="mt-3 text-sm text-white/50">Km du mois : <strong className="text-white">{km.toFixed(0)} km</strong></p></section>
  <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><h2 className="text-lg font-semibold text-white">Honoraires du mois</h2><p className="mt-1 text-xs text-white/40">Du plus récent au plus ancien.</p><div className="mt-4 space-y-2">{fees.length?fees.map((f:any)=><form action={updateFee} key={f.id} className="osteo-row grid gap-2 rounded-2xl border border-white/10 bg-[#292B28] p-3 sm:grid-cols-[150px_150px_1fr_auto_auto] sm:items-center"><input type="hidden" name="id" value={f.id}/><input type="date" name="fee_date" defaultValue={f.fee_date} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><select name="payment_method" defaultValue={f.payment_method} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"><option value="cb">CB</option><option value="cash">Espèces</option><option value="cheque">Chèque</option></select><input name="amount" type="number" step="0.01" min="0.01" defaultValue={Number(f.amount)} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><button className="rounded-xl border border-[#D2AE57]/35 px-3 py-2 text-sm text-[#E0C27E]">Modifier</button><button formAction={deleteFee} className="rounded-xl border border-red-500/30 px-3 py-2 text-sm text-red-300">Supprimer</button></form>):<p className="text-sm text-white/45">Aucun honoraire pour ce mois.</p>}</div></section>
  <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Charges du mois</h2><span className="text-sm text-white/45">{money(expenses)}</span></div><div className="mt-4 space-y-2">{charges.map((c:any)=><form action={updateCharge} key={c.id} className="osteo-row grid gap-2 rounded-2xl border border-white/10 bg-[#292B28] p-3 md:grid-cols-[70px_1fr_130px_130px_150px_auto] md:items-center"><input type="hidden" name="id" value={c.id}/><input name="due_day" type="number" min="1" max="31" defaultValue={c.due_day} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><input name="label" defaultValue={c.label} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><input name="amount" type="number" step="0.01" min="0" defaultValue={Number(c.amount)} className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-2 py-2 text-white"/><label className="flex items-center gap-2 text-sm text-white/65"><input className="osteo-check" name="paid" type="checkbox" defaultChecked={c.paid}/>Payée</label><label className="flex items-center gap-2 text-sm text-white/65"><input className="osteo-check" name="project_to_personal" type="checkbox" defaultChecked={c.project_to_personal}/>Vers PERSO</label><button className="rounded-xl border border-[#D2AE57]/35 px-3 py-2 text-sm text-[#E0C27E]">Enregistrer</button></form>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-[#E0C27E]">+ Ajouter une charge</summary><form action={createCharge} className="mt-3 grid gap-2 sm:grid-cols-4"><input type="hidden" name="month" value={selected}/><input name="due_day" type="number" min="1" max="31" defaultValue="1" className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-3 py-2 text-white"/><input name="label" placeholder="Libellé" required className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-3 py-2 text-white"/><input name="amount" type="number" step="0.01" min="0" placeholder="Montant" className="osteo-input rounded-xl border border-white/10 bg-[#343632] px-3 py-2 text-white"/><label className="flex items-center gap-2 text-sm text-white/65"><input className="osteo-check" name="project_to_personal" type="checkbox"/>Projeter dans PERSO</label><button className="rounded-xl bg-[#D2AE57] px-4 py-2 font-semibold text-black sm:col-span-4">Ajouter</button></form></details></section>
 </>
}

function Annual2035({year,annual}:{year:number;annual:AnnualMonth[]}){return <section className="osteo-panel overflow-hidden rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-white/40">Déclaration 2035</p><h2 className="mt-1 text-xl font-semibold text-white">Vue annuelle {year}</h2></div><div className="flex gap-2"><a href={`/osteo/export?scope=year&year=${year}`} className="osteo-secondary-button"><Download size={15}/>Exporter PDF 2035</a><form action="/osteo" className="flex gap-2"><input type="hidden" name="view" value="2035"/><input name="year" type="number" defaultValue={year} className="osteo-input w-24 rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2 text-white"/><button className="osteo-secondary-button">Afficher</button></form></div></div><div className="mt-5 overflow-x-auto"><table className="osteo-2035-table min-w-[1300px] w-full border-collapse text-sm"><thead><tr><Th>2035</Th>{annual.map(x=><Th key={x.k}><Link href={`/osteo?view=mensuel&month=${x.k}&year=${year}`} className="hover:text-[#E0C27E]">{shortMonth(x.k)}</Link></Th>)}<Th>Total par ligne</Th></tr></thead><tbody><GroupRow group="Revenus" tone="income" label="Chèques et CB" values={annual.map(x=>x.cbCheque)}/><AnnualRow label="Espèces" values={annual.map(x=>x.cash)}/><AnnualRow label="Sous loc" values={annual.map(x=>x.sublet)}/><AnnualRow label="Total revenus" values={annual.map(x=>x.total)} strong tone="income-total"/><Spacer/><GroupRow group="Dépenses" tone="expense" label={CORE_LABELS[CORE_ORDER[0]]} values={annual.map(x=>Number(x.charges.find((c:any)=>c.category_key===CORE_ORDER[0])?.amount||0))}/>{CORE_ORDER.slice(1).map(key=><AnnualRow key={key} label={CORE_LABELS[key]} values={annual.map(x=>Number(x.charges.find((c:any)=>c.category_key===key)?.amount||0))}/>) }<AnnualRow label="Dépenses" values={annual.map(x=>x.expenses)} strong tone="expense-total"/><Spacer/><AnnualRow label={`Bénéfice ${year}`} values={annual.map(x=>x.benefit)} strong tone="benefit"/><AnnualRow label="Nbr patients" values={annual.map(x=>x.patients)} plain tone="stats"/><AnnualRow label="Nbre de jours" values={annual.map(x=>x.days)} plain tone="stats"/><AnnualRow label="Km/mois" values={annual.map(x=>x.km)} plain tone="stats"/><AnnualRow label={`Bénéfices ${year-1}`} values={annual.map(x=>x.prev)} tone="previous"/></tbody></table></div><p className="mt-4 text-xs text-white/45">Présentation et ordre des lignes repris de l’onglet 2035 du fichier fourni. Les cellules se modifient depuis la vue mensuelle correspondante.</p></section>}

function AnalysisView({year,annual,currentMonth}:{year:number;annual:AnnualMonth[];currentMonth:string}){
 const pastOrCurrent=annual.filter(x=>x.k<=currentMonth && x.patients>0); const ytdPatients=pastOrCurrent.reduce((s,x)=>s+x.patients,0); const ytdCa=pastOrCurrent.reduce((s,x)=>s+x.cbCheque+x.cash,0); const avgFee=ytdPatients>0?ytdCa/ytdPatients:60;
 return <section className="osteo-panel rounded-3xl border border-white/10 bg-[#1B1D1B] p-5"><div><p className="text-xs uppercase tracking-[.18em] text-white/40">Analyse</p><h2 className="mt-1 text-xl font-semibold text-white">Synthèse mensuelle {year}</h2><p className="mt-1 text-sm text-white/50">CA = honoraires CB + chèques + espèces. L’équilibre tient compte des charges et de la sous-location. Aucun objectif n’est injecté dans Projection.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Metric label="CA réalisé année" value={money(ytdCa)}/><Metric label="Patients réalisés" value={String(ytdPatients)}/><Metric label="Honoraire moyen réalisé" value={money(avgFee)}/></div><div className="mt-5 overflow-x-auto"><table className="min-w-[980px] w-full border-collapse text-sm"><thead><tr><Th>Mois</Th><Th>CA total</Th><Th>Charges</Th><Th>Patients réalisés</Th><Th>CA d’équilibre</Th><Th>Patients nécessaires à l’équilibre</Th><Th>Résultat</Th></tr></thead><tbody>{annual.map(x=>{const ca=x.cbCheque+x.cash;const equilibrium=Math.max(0,x.expenses-x.sublet);const needed=avgFee>0?Math.ceil(equilibrium/avgFee):0;const future=x.k>currentMonth;return <tr key={x.k} className={future?"osteo-analysis-future":""}><td className="border-b border-white/8 px-3 py-2 font-semibold text-white"><Link href={`/osteo?view=mensuel&month=${x.k}&year=${year}`}>{monthName(x.k)}</Link></td><td className="border-b border-white/8 px-3 py-2 text-right text-white/75">{money(ca)}</td><td className="border-b border-white/8 px-3 py-2 text-right text-white/75">{money(x.expenses)}</td><td className="border-b border-white/8 px-3 py-2 text-right text-white/75">{x.patients}</td><td className="border-b border-white/8 px-3 py-2 text-right text-[#E0C27E]">{money(equilibrium)}</td><td className="border-b border-white/8 px-3 py-2 text-right text-[#E0C27E]">{needed}</td><td className={`border-b border-white/8 px-3 py-2 text-right font-semibold ${x.benefit>=0?"text-emerald-300":"text-red-300"}`}>{money(x.benefit)}</td></tr>})}</tbody></table></div><p className="mt-4 text-xs text-white/45">Pour les mois à venir, le nombre de patients nécessaire est calculé avec l’honoraire moyen réellement constaté depuis le début de l’année ({money(avgFee)} par patient).</p></section>}

function pMonth(v:string|undefined,fallback:string){return v&&/^\d{4}-\d{2}$/.test(v)?v:fallback}
function NavButton({active,href,icon,children}:{active:boolean;href:string;icon:React.ReactNode;children:React.ReactNode}){return <Link prefetch={false} href={href} className={`inline-flex items-center gap-2 rounded-2xl px-4 py-2.5 text-sm font-semibold ${active?"bg-[#D2AE57] text-black":"bg-white/8 text-white"}`}>{icon}{children}</Link>}
function Metric({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div className="osteo-metric rounded-2xl border border-white/10 bg-[#292B28] p-3"><p className="text-xs text-white/45">{label}</p><p className={`mt-1 text-lg font-semibold ${accent===undefined?"text-white":accent?"text-emerald-300":"text-red-300"}`}>{value}</p></div>}
function Field({name,label,value}:{name:string;label:string;value:number}){return <label className="text-sm text-white/65">{label}<input name={name} type="number" step="0.01" defaultValue={value} className="osteo-input mt-1 w-full rounded-xl border border-white/15 bg-[#2A2D2A] px-3 py-2.5 text-white"/></label>}
function Th({children}:{children:React.ReactNode}){return <th className="border border-white/10 bg-[#222422] px-3 py-2 text-right text-xs font-semibold text-white first:text-left">{children}</th>}
function Spacer(){return <tr><td colSpan={14} className="h-2 bg-transparent"/></tr>}
function GroupRow({group,tone,label,values}:{group:string;tone:string;label:string;values:number[]}){return <tr><td className={`osteo-2035-group osteo-2035-${tone} border border-white/10 px-3 py-2 font-semibold text-white`}><span className="block text-[10px] uppercase tracking-[.12em] opacity-70">{group}</span>{label}</td>{values.map((v,i)=><td key={i} className="border border-white/10 px-3 py-2 text-right text-white/75">{money(v)}</td>)}<td className="border border-white/10 px-3 py-2 text-right font-semibold text-[#E0C27E]">{money(values.reduce((s,v)=>s+Number(v||0),0))}</td></tr>}
function AnnualRow({label,values,strong=false,plain=false,tone}:{label:string;values:number[];strong?:boolean;plain?:boolean;tone?:string}){const total=values.reduce((s,v)=>s+Number(v||0),0);return <tr className={`${strong?"font-semibold":""} ${tone?`osteo-2035-${tone}`:""}`}><td className="border border-white/10 px-3 py-2 text-white">{label}</td>{values.map((v,i)=><td key={i} className="border border-white/10 px-3 py-2 text-right text-white/75">{plain?Number(v||0).toFixed(0):money(v)}</td>)}<td className="border border-white/10 px-3 py-2 text-right text-[#E0C27E]">{plain?total.toFixed(0):money(total)}</td></tr>}
